/*
 * InterfaceComandosSlider.java
 *
 * Created on 15/06/2009
 */

package com.hdntec.gestao.cliente.interfaceDeDialogo.interfaceComandos;

import com.hdntec.gestao.cliente.interfaceDeDialogo.InterfaceInicial;
import com.hdntec.gestao.util.PropertiesUtil;

/**
 *
 * @author Bruno Gomes
 */
public class InterfaceComandosSlider extends javax.swing.JPanel {

      /** acesso às operações do subsistema de interface gráfica de comandos */
    private ControladorInterfaceComandos controladorInterfaceComandos;

     /** interface gráfica principal do sistema */
    private InterfaceInicial interfaceInicial;

    /** Creates new form InterfaceComandosSlider */
    public InterfaceComandosSlider() {
        initComponents();
        //ajustando tamanho do painel
        this.setBounds(0, 0, 200, 63);
    }

    /**
     * Metodo que desabilita todas as funcionalidades do sistema como os
     * botoes de comando e opcoes de edicao quando o sistema estiver processamento
     * alguma operacao.
     */
    public void desabilitarTodasFuncoes() {
        // desabilitando botoes de comando
        cmbPrimeiro.setEnabled(false);
        cmbUltimo.setEnabled(false);
        cmdAnterior.setEnabled(false);
        cmdProximo.setEnabled(false);
         // desabilitando o slider de navegacao
        controladorInterfaceComandos.getInterfaceInicial().getInterfaceInicial().getSliderNavegacao().setEnabled(false);

        // desabilitando os menus de edicao dos objetos
        controladorInterfaceComandos.desabilitarMenusDeEdicao();
    }

    /**
     * Metodo que habilita todas as funcionalidades do sistema como os
     * botoes de comando e opcoes de edicao quando o sistema estiver processamento
     * alguma operacao.
     */
    public void habilitarTodasFuncoes() {
        // habilitando botoes de comando
        cmbPrimeiro.setEnabled(true);
        cmbUltimo.setEnabled(true);
        cmdAnterior.setEnabled(true);
        cmdProximo.setEnabled(true);
          // habilitando o slider de navegacao
        controladorInterfaceComandos.getInterfaceInicial().getInterfaceInicial().getSliderNavegacao().setEnabled(true);

        // Habilitando os menus de edicao dos objetos
        controladorInterfaceComandos.habilitarMenusDeEdicao();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      cmbPrimeiro = new javax.swing.JButton();
      cmdAnterior = new javax.swing.JButton();
      cmdProximo = new javax.swing.JButton();
      cmbUltimo = new javax.swing.JButton();

      setMaximumSize(new java.awt.Dimension(327, 327));
      setMinimumSize(new java.awt.Dimension(200, 63));
      setPreferredSize(new java.awt.Dimension(200, 63));
      setLayout(null);

      cmbPrimeiro.setIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar_tudo-a.png"));
      cmbPrimeiro.setPressedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar_tudo-b.png"));
      cmbPrimeiro.setRolloverIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar_tudo-c.png"));
      cmbPrimeiro.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbPrimeiroActionPerformed(evt);
         }
      });
      add(cmbPrimeiro);
      cmbPrimeiro.setBounds(10, 15, 35, 27);

      cmdAnterior.setIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar-a.png"));
      cmdAnterior.setPressedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar-b.png"));
      cmdAnterior.setRolloverIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/voltar-c.png"));
      cmdAnterior.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmdAnteriorActionPerformed(evt);
         }
      });
      add(cmdAnterior);
      cmdAnterior.setBounds(51, 15, 35, 27);

      cmdProximo.setIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir-a.png"));
      cmdProximo.setPressedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir-b.png"));
      cmdProximo.setRolloverIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir-c.png"));
      cmdProximo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmdProximoActionPerformed(evt);
         }
      });
      add(cmdProximo);
      cmdProximo.setBounds(102, 15, 35, 27);

      cmbUltimo.setIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir_tudo-a.png"));
      cmbUltimo.setPressedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir_tudo-b.png"));
      cmbUltimo.setRolloverIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir_tudo-c.png"));
      cmbUltimo.setRolloverSelectedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir_tudo-c.png"));
      cmbUltimo.setSelectedIcon(new javax.swing.ImageIcon(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens") + "/prosseguir_tudo-b.png"));
      cmbUltimo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbUltimoActionPerformed(evt);
         }
      });
      add(cmbUltimo);
      cmbUltimo.setBounds(153, 15, 35, 27);
   }// </editor-fold>//GEN-END:initComponents

    private void cmbPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrimeiroActionPerformed
        controladorInterfaceComandos.getInterfaceInicial().exibirPrimeiraSituacaoPatio();
}//GEN-LAST:event_cmbPrimeiroActionPerformed

    private void cmdAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnteriorActionPerformed
        controladorInterfaceComandos.getInterfaceInicial().exibirSituacaoPatioAnterior();
}//GEN-LAST:event_cmdAnteriorActionPerformed

    private void cmdProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProximoActionPerformed
        controladorInterfaceComandos.getInterfaceInicial().exibirSituacaoPatioPosterior();
}//GEN-LAST:event_cmdProximoActionPerformed

    private void cmbUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUltimoActionPerformed
        controladorInterfaceComandos.getInterfaceInicial().exibirUltimaSituacaoPatio();
}//GEN-LAST:event_cmbUltimoActionPerformed

    public InterfaceInicial getInterfaceInicial() {
        return interfaceInicial;
    }

    public void setInterfaceInicial(InterfaceInicial interfaceInicial) {
        this.interfaceInicial = interfaceInicial;
    }

    public ControladorInterfaceComandos getControladorInterfaceComandos() {
        return controladorInterfaceComandos;
    }

    public void setControladorInterfaceComandos(ControladorInterfaceComandos controladorInterfaceComandos) {
        this.controladorInterfaceComandos = controladorInterfaceComandos;
        this.controladorInterfaceComandos.setInterfaceComandosSlider(this);
    }

    

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cmbPrimeiro;
   private javax.swing.JButton cmbUltimo;
   private javax.swing.JButton cmdAnterior;
   private javax.swing.JButton cmdProximo;
   // End of variables declaration//GEN-END:variables

}
