/*
 * InterfaceBuscarPlanoOficial.java
 *
 * Created on 19/02/2009, 18:16:26
 */

package com.hdntec.gestao.cliente.interfaceDeDialogo.interfaceComandos;

import java.util.Date;

import com.hdntec.gestao.cliente.messagens.InterfaceMensagem;
import com.hdntec.gestao.exceptions.ValidacaoCampoException;
import com.hdntec.gestao.util.PropertiesUtil;
import com.hdntec.gestao.util.datahora.DSSStockyardTimeUtil;

/**
 *
 * @author Bruno Gomes
 */
public class InterfaceBuscarPlanoOficial extends javax.swing.JDialog {

    private ControladorInterfaceComandos controladorInterfaceComandos;
    private Date dataInicial;
    private Date dataFinal;

    /** Creates new form InterfaceBuscarPlanoOficial */
    public InterfaceBuscarPlanoOficial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtIniCalendarioHoraCflex.limpaDataHora();
        dtFimCalendarioHoraCFlex.limpaDataHora();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbConfirmar = new javax.swing.JButton();
        jcCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtIniCalendarioHoraCflex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();
        dtFimCalendarioHoraCFlex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(PropertiesUtil.getMessage("titulo.Carregar.plano.oficial"));
        StringBuffer value = new StringBuffer();
        value.append(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens")).append("/confirmar.png");
        jbConfirmar.setIcon(new javax.swing.ImageIcon(value.toString())); // NOI18N
        jbConfirmar.setText(PropertiesUtil.getMessage("botao.confirmar"));
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });
        value = new StringBuffer();
        value.append(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens")).append("/cancelar.png");
        jcCancelar.setIcon(new javax.swing.ImageIcon(value.toString())); // NOI18N
        jcCancelar.setText(PropertiesUtil.getMessage("botao.cancelar"));
        jcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText(PropertiesUtil.getMessage("label.data.inicial.sem.dois.pontos"));

        jLabel2.setText(PropertiesUtil.getMessage("label.data.final.sem.dois.pontos"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtIniCalendarioHoraCflex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(dtFimCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtIniCalendarioHoraCflex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dtFimCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConfirmar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmar)
                    .addComponent(jcCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        try {
            validarInformacoes();
            //controladorInterfaceComandos.buscarPlanoEmpilhamentoRecuperacaoDoUsuario(dataInicial, dataFinal);
            this.setVisible(false);
        } catch (ValidacaoCampoException ex) {
        	controladorInterfaceComandos.getInterfaceInicial().desativarMensagemProcessamento();
            InterfaceMensagem interfaceMensagem = new InterfaceMensagem();
            interfaceMensagem.setTipoMensagem(InterfaceMensagem.MENSAGEM_TIPO_ALERTA);
            interfaceMensagem.setDescricaoMensagem(ex.getMessage());
            controladorInterfaceComandos.ativarMensagem(interfaceMensagem);
        }

    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void validarInformacoes() throws ValidacaoCampoException {

        DSSStockyardTimeUtil.validarDataHora(dtIniCalendarioHoraCflex.getDataHora(), PropertiesUtil.getMessage("aviso.validacao.data.inicial"));
        dataInicial = DSSStockyardTimeUtil.criaDataComString(dtIniCalendarioHoraCflex.getDataHora(), PropertiesUtil.buscarPropriedade("formato.campo.datahora"));

        DSSStockyardTimeUtil.validarDataHora(dtFimCalendarioHoraCFlex.getDataHora(), PropertiesUtil.getMessage("aviso.validacao.data.final"));
        dataFinal = DSSStockyardTimeUtil.criaDataComString(dtFimCalendarioHoraCFlex.getDataHora(), PropertiesUtil.buscarPropriedade("formato.campo.datahora"));

        if (dataFinal.compareTo(dataInicial) < 0) {
            throw new ValidacaoCampoException(PropertiesUtil.getMessage("aviso.a.data.final.deve.ser.maior.ou.igual.data.inicial"));
        }
    }


    private void jcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jcCancelarActionPerformed

    public ControladorInterfaceComandos getControladorInterfaceComandos() {
        return controladorInterfaceComandos;
    }

    public void setControladorInterfaceComandos(ControladorInterfaceComandos controladorInterfaceComandos) {
        this.controladorInterfaceComandos = controladorInterfaceComandos;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtFimCalendarioHoraCFlex;
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtIniCalendarioHoraCflex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jcCancelar;
    // End of variables declaration//GEN-END:variables

}
