/*
 * InterfaceInserirNavioFilaDeNavios.java
 *
 * Created on 05/05/2009, 16:26:18
 */

package com.hdntec.gestao.cliente.interfaceDeDialogo.interfaceDeFilaDeNavios;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JTextField;

import com.hdntec.gestao.cliente.messagens.InterfaceMensagem;
import com.hdntec.gestao.cliente.util.ComboBoxRederer;
import com.hdntec.gestao.cliente.util.telas.DSSStockyardTelaUtil;
import com.hdntec.gestao.exceptions.ValidacaoCampoException;
import com.hdntec.gestao.util.PropertiesUtil;

/**
 *
 * @author guilherme
 */
public abstract class InterfaceInserirNavioFilaDeNavios extends javax.swing.JPanel {

    private Boolean operacaoCanceladaPeloUsuario = Boolean.FALSE;
    private EditarInserirDadosNavioNaFilaDeNavios editarInserirDadosNavioNaFilaDeNavios = new EditarInserirDadosNavioNaFilaDeNavios(this);
    private InterfaceNavio interfaceNavio;
    private ControladorInterfaceFilaDeNavios controladorInterfaceFilaDeNavios;
    private String[] tooltips = {PropertiesUtil.getMessage("tooltip.nao.confirmado"), PropertiesUtil.getMessage("tooltip.confirmado"), PropertiesUtil.getMessage("tooltip.nabarra"), PropertiesUtil.getMessage("tooltip.atracado"), PropertiesUtil.getMessage("tooltip.embarcado")};
    private boolean novoClienteCriado = Boolean.FALSE;

    /** Creates new form InterfaceInserirNavioFilaDeNavios */
    public InterfaceInserirNavioFilaDeNavios(InterfaceNavio interfaceNavio, ControladorInterfaceFilaDeNavios controladorInterfaceFilaDeNavios) {
        editarInserirDadosNavioNaFilaDeNavios.setControladorInterfaceFilaDeNavios(controladorInterfaceFilaDeNavios);
        this.interfaceNavio = interfaceNavio;
        initComponents();
        insereToolTipComboBox();
        editarInserirDadosNavioNaFilaDeNavios.habilitaInserir();
        editarInserirDadosNavioNaFilaDeNavios.inicializaCamposValorZero();
        eventoComboBox();
        desabilitaItens();
        lblStatus2.setVisible(Boolean.FALSE);
        txtTaxaEstadia.setVisible(Boolean.FALSE);
    }

    private void insereToolTipComboBox() {
        ComboBoxRederer comboBoxRederer = new ComboBoxRederer();
        comboBoxRederer.setTooltips(tooltips);
        //adiciona do comboBox status do Navio
        getCmbStatus().setRenderer(comboBoxRederer);
    }

    /**
     * Metodo criado abstrato, pois sua implementacao sera na classe que o instanciou
     */
    public abstract void fecharJanela();
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeNavio = new javax.swing.JLabel();
        lblDwt = new javax.swing.JLabel();
        lblEta = new javax.swing.JLabel();
        etaCalendarioHoraCFlex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();
        txtDwt = new javax.swing.JTextField();
        txtNomeNavio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDtChegada = new javax.swing.JLabel();
        lblDtEmbarque = new javax.swing.JLabel();
        lblDtSaida = new javax.swing.JLabel();
        dtChegadaCalendarioHoraCFlex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();
        dtEmbarqueCalendarioHoraCFlex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();
        dtSaidaCalendarioHoraCFlex = new com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex();
        jPanel3 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox();
        cmbCliente = new javax.swing.JComboBox();
        cmdNovoCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnDesistir = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblStatus1 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblStatus3 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtTaxaEstadia = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir navio na fila"));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNomeNavio.setText("Navio");

        lblDwt.setText("Dwt");

        lblEta.setText("ETA");

        txtDwt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDwtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeNavio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeNavio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDwt)
                        .addGap(18, 18, 18)
                        .addComponent(txtDwt)))
                .addGap(57, 57, 57)
                .addComponent(lblEta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etaCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeNavio)
                    .addComponent(txtNomeNavio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDwt)
                    .addComponent(lblEta)
                    .addComponent(txtDwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(etaCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDtChegada.setText("Data de chegada");

        lblDtEmbarque.setText("Data de atracação");

        lblDtSaida.setText("Data de saída");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDtChegada)
                        .addGap(18, 18, 18)
                        .addComponent(dtChegadaCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblDtSaida)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtSaidaCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblDtEmbarque)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dtEmbarqueCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDtChegada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtChegadaCalendarioHoraCFlex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dtEmbarqueCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDtEmbarque)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDtSaida)
                    .addComponent(dtSaidaCalendarioHoraCFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStatus.setText("Status");

        jLabel5.setText("Cliente");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "C", "B", "A", "E" }));

        cmdNovoCliente.setText("Novo Cliente");
        cmdNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNovoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cmdNovoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(cmdNovoCliente)
                .addGap(23, 23, 23))
        );

        StringBuffer value = new StringBuffer();
        value.append(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens")).append("/exit.png");
        btnDesistir.setIcon(new javax.swing.ImageIcon(value.toString())); // NOI18N        
        btnDesistir.setText("Desistir");
        btnDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesistirActionPerformed(evt);
            }
        });

        value = new StringBuffer();
        value.append(PropertiesUtil.buscarPropriedade("tela.diretorio.imagens")).append("/confirmar.png");
        btnConfirmar.setIcon(new javax.swing.ImageIcon(value.toString())); // NOI18N                
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStatus1.setText("Nome cliente:");

        lblStatus2.setText("Taxa de Estadia:");

        lblStatus3.setText("Código cliente:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus1)
                            .addComponent(lblStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaxaEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblStatus3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus1)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaxaEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDesistir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnDesistir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (editarInserirDadosNavioNaFilaDeNavios.validaDados(interfaceNavio)) {
            //fecha janela
            this.operacaoCanceladaPeloUsuario = Boolean.FALSE;
            DSSStockyardTelaUtil.getParentDialog(this).setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesistirActionPerformed
        fecharJanela();
        DSSStockyardTelaUtil.getParentDialog(this).setVisible(false);
    }//GEN-LAST:event_btnDesistirActionPerformed

    private void txtDwtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDwtKeyReleased
        try{
            if(txtDwt.getText().length() > 15){
                txtDwt.setForeground(Color.RED);
                List<String> listaParametros = new ArrayList<String>();
                listaParametros.add(txtDwt.getText());
                listaParametros.add("15");
                throw new ValidacaoCampoException("exception.validacao.tamanho.de.campo", listaParametros);
            }else{
                txtDwt.setForeground(Color.BLACK);
            }
        }catch(ValidacaoCampoException ex){
        	interfaceNavio.getControladorInterfaceFilaDeNavios().getInterfaceInicial().desativarMensagemProcessamento();
            InterfaceMensagem interfaceMensagem = new InterfaceMensagem();
            interfaceMensagem.setTipoMensagem(InterfaceMensagem.MENSAGEM_TIPO_ALERTA);
            interfaceMensagem.setDescricaoMensagem(ex.getMessage());
            interfaceNavio.getControladorInterfaceFilaDeNavios().ativarMensagem(interfaceMensagem);
        }
    }//GEN-LAST:event_txtDwtKeyReleased

    private void cmdNovoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdNovoClienteActionPerformed
    {//GEN-HEADEREND:event_cmdNovoClienteActionPerformed
        habilitaItens();
        novoClienteCriado = Boolean.TRUE;
    }//GEN-LAST:event_cmdNovoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDesistir;
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JButton cmdNovoCliente;
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtChegadaCalendarioHoraCFlex;
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtEmbarqueCalendarioHoraCFlex;
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtSaidaCalendarioHoraCFlex;
    private com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex etaCalendarioHoraCFlex;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDtChegada;
    private javax.swing.JLabel lblDtEmbarque;
    private javax.swing.JLabel lblDtSaida;
    private javax.swing.JLabel lblDwt;
    private javax.swing.JLabel lblEta;
    private javax.swing.JLabel lblNomeNavio;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDwt;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeNavio;
    private javax.swing.JTextField txtTaxaEstadia;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the operacaoCanceladaPeloUsuario
     */
    public Boolean getOperacaoCanceladaPeloUsuario() {
        return operacaoCanceladaPeloUsuario;
    }

    /**
     * @param operacaoCanceladaPeloUsuario the operacaoCanceladaPeloUsuario to set
     */
    public void setOperacaoCanceladaPeloUsuario(Boolean operacaoCanceladaPeloUsuario) {
        this.operacaoCanceladaPeloUsuario = operacaoCanceladaPeloUsuario;
    }

    /**
     * @return the editarInserirDadosNavioNaFilaDeNavios
     */
    public EditarInserirDadosNavioNaFilaDeNavios getEditarInserirDadosNavioNaFilaDeNavios() {
        return editarInserirDadosNavioNaFilaDeNavios;
    }

    /**
     * @param editarInserirDadosNavioNaFilaDeNavios the editarInserirDadosNavioNaFilaDeNavios to set
     */
    public void setEditarInserirDadosNavioNaFilaDeNavios(EditarInserirDadosNavioNaFilaDeNavios editarInserirDadosNavioNaFilaDeNavios) {
        this.editarInserirDadosNavioNaFilaDeNavios = editarInserirDadosNavioNaFilaDeNavios;
    }

    /**
     * @return the interfaceNavio
     */
    public InterfaceNavio getInterfaceNavio() {
        return interfaceNavio;
    }

    /**
     * @param interfaceNavio the interfaceNavio to set
     */
    public void setInterfaceNavio(InterfaceNavio interfaceNavio) {
        this.interfaceNavio = interfaceNavio;
    }

    /**
     * @return the controladorInterfaceFilaDeNavios
     */
    public ControladorInterfaceFilaDeNavios getControladorInterfaceFilaDeNavios() {
        return controladorInterfaceFilaDeNavios;
    }

    /**
     * @param controladorInterfaceFilaDeNavios the controladorInterfaceFilaDeNavios to set
     */
    public void setControladorInterfaceFilaDeNavios(ControladorInterfaceFilaDeNavios controladorInterfaceFilaDeNavios) {
        this.controladorInterfaceFilaDeNavios = controladorInterfaceFilaDeNavios;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    /**
     * @param btnConfirmar the btnConfirmar to set
     */
    public void setBtnConfirmar(javax.swing.JButton btnConfirmar) {
        this.btnConfirmar = btnConfirmar;
    }

    /**
     * @return the btnDesistir
     */
    public javax.swing.JButton getBtnDesistir() {
        return btnDesistir;
    }

    /**
     * @param btnDesistir the btnDesistir to set
     */
    public void setBtnDesistir(javax.swing.JButton btnDesistir) {
        this.btnDesistir = btnDesistir;
    }

    /**
     * @return the cmbCliente
     */
    public javax.swing.JComboBox getCmbCliente() {
        return cmbCliente;
    }

    /**
     * @param cmbCliente the cmbCliente to set
     */
    public void setCmbCliente(javax.swing.JComboBox cmbCliente) {
        this.cmbCliente = cmbCliente;
    }

    /**
     * @return the cmbStatus
     */
    public javax.swing.JComboBox getCmbStatus() {
        return cmbStatus;
    }

    /**
     * @param cmbStatus the cmbStatus to set
     */
    public void setCmbStatus(javax.swing.JComboBox cmbStatus) {
        this.cmbStatus = cmbStatus;
    }

    /**
     * @return the dtChegadaCalendarioHoraCFlex
     */
    public com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex getDtChegadaCalendarioHoraCFlex() {
        return dtChegadaCalendarioHoraCFlex;
    }

    /**
     * @param dtChegadaCalendarioHoraCFlex the dtChegadaCalendarioHoraCFlex to set
     */
    public void setDtChegadaCalendarioHoraCFlex(com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtChegadaCalendarioHoraCFlex) {
        this.dtChegadaCalendarioHoraCFlex = dtChegadaCalendarioHoraCFlex;
    }

    /**
     * @return the dtEmbarqueCalendarioHoraCFlex
     */
    public com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex getDtEmbarqueCalendarioHoraCFlex() {
        return dtEmbarqueCalendarioHoraCFlex;
    }

    /**
     * @param dtEmbarqueCalendarioHoraCFlex the dtEmbarqueCalendarioHoraCFlex to set
     */
    public void setDtEmbarqueCalendarioHoraCFlex(com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtEmbarqueCalendarioHoraCFlex) {
        this.dtEmbarqueCalendarioHoraCFlex = dtEmbarqueCalendarioHoraCFlex;
    }

    /**
     * @return the dtSaidaCalendarioHoraCFlex
     */
    public com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex getDtSaidaCalendarioHoraCFlex() {
        return dtSaidaCalendarioHoraCFlex;
    }

    /**
     * @param dtSaidaCalendarioHoraCFlex the dtSaidaCalendarioHoraCFlex to set
     */
    public void setDtSaidaCalendarioHoraCFlex(com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex dtSaidaCalendarioHoraCFlex) {
        this.dtSaidaCalendarioHoraCFlex = dtSaidaCalendarioHoraCFlex;
    }

    /**
     * @return the etaCalendarioHoraCFlex
     */
    public com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex getEtaCalendarioHoraCFlex() {
        return etaCalendarioHoraCFlex;
    }

    /**
     * @param etaCalendarioHoraCFlex the etaCalendarioHoraCFlex to set
     */
    public void setEtaCalendarioHoraCFlex(com.hdntec.gestao.cliente.util.datahora.CalendarioHoraCFlex etaCalendarioHoraCFlex) {
        this.etaCalendarioHoraCFlex = etaCalendarioHoraCFlex;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getJLabel5() {
        return jLabel5;
    }

    /**
     * @return the lblDtChegada
     */
    public javax.swing.JLabel getLblDtChegada() {
        return lblDtChegada;
    }

    /**
     * @return the lblDtEmbarque
     */
    public javax.swing.JLabel getLblDtEmbarque() {
        return lblDtEmbarque;
    }

    /**
     * @return the lblDtSaida
     */
    public javax.swing.JLabel getLblDtSaida() {
        return lblDtSaida;
    }

    /**
     * @return the lblDwt
     */
    public javax.swing.JLabel getLblDwt() {
        return lblDwt;
    }

    /**
     * @return the lblEta
     */
    public javax.swing.JLabel getLblEta() {
        return lblEta;
    }

    /**
     * @return the lblNomeNavio
     */
    public javax.swing.JLabel getLblNomeNavio() {
        return lblNomeNavio;
    }

    /**
     * @return the lblStatus
     */
    public javax.swing.JLabel getLblStatus() {
        return lblStatus;
    }

    /**
     * @return the txtDwt
     */
    public javax.swing.JTextField getTxtDwt() {
        return txtDwt;
    }

    /**
     * @param txtDwt the txtDwt to set
     */
    public void setTxtDwt(javax.swing.JTextField txtDwt) {
        this.txtDwt = txtDwt;
    }

    /**
     * @return the txtNomeNavio
     */
    public javax.swing.JTextField getTxtNomeNavio() {
        return txtNomeNavio;
    }

    /**
     * @param txtNomeNavio the txtNomeNavio to set
     */
    public void setTxtNomeNavio(javax.swing.JTextField txtNomeNavio) {
        this.txtNomeNavio = txtNomeNavio;
    }

    private void eventoComboBox(){
        cmbCliente.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent evt) {
                cmdClienteItemStateChanged(evt);
            }
        });
    }

    private void cmdClienteItemStateChanged(ItemEvent evt)
    {
        //if(getCmbCliente().getSelectedItem().equals(PropertiesUtil.getMessage("combo.novo.cliente")) ){
            cmdNovoCliente.setEnabled(true);
        //}
        //else{
            //cmdNovoCliente.setEnabled(false);
        //}
    }

    /**
     * mantem os itens de inserir novo cliente desabilitados
     */
    private void desabilitaItens(){
        //campos de texto
        txtCodigoCliente.setEnabled(false);
        txtNomeCliente.setEnabled(false);
        txtTaxaEstadia.setEnabled(false);
        //labels
        lblStatus1.setEnabled(false);
        lblStatus2.setEnabled(false);
        lblStatus3.setEnabled(false);
    }

     /**
     * mantem os itens de inserir novo cliente habilitados
     */
    private void habilitaItens(){
        //campos de texto
        txtCodigoCliente.setEnabled(true);
        txtNomeCliente.setEnabled(true);
        txtTaxaEstadia.setEnabled(true);
        //labels
        lblStatus1.setEnabled(true);
        lblStatus2.setEnabled(true);
        lblStatus3.setEnabled(true);
        //desabilita combo de cliente
        cmbCliente.setEnabled(false);
        cmdNovoCliente.setEnabled(false);
    }

    public boolean isNovoClienteCriado() {
        return novoClienteCriado;
    }

    public JTextField getTxtCodigoCliente() {
        return txtCodigoCliente;
    }

    public JTextField getTxtNomeCliente() {
        return txtNomeCliente;
    }

    public JTextField getTxtTaxaEstadia() {
        return txtTaxaEstadia;
    }

    /**
     * nome do cliente
     * @return
     */
    public JLabel getLblStatus1() {
        return lblStatus1;
    }

    /**
     * taxa de estadia
     * @return
     */
    public JLabel getLblStatus2() {
        return lblStatus2;
    }

    /**
     * codigo do cliente
     * @return
     */
    public JLabel getLblStatus3() {
        return lblStatus3;
    }
    
    
}
