/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogonPromptDialog.java
 *
 * Created on 06/05/2009, 10:26:10
 */
package com.hdntec.gestao.login.ws.service;

import java.io.ByteArrayInputStream;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.namespace.QName;
import javax.xml.rpc.ServiceException;

import org.apache.axis.client.Call;
import org.apache.axis.client.Service;

import com.hdntec.gestao.login.entity.User;


import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 *
 * @author doleron
 */
public class LogonPromptDialog extends javax.swing.JDialog {

    private User user;
    private String endpoint;
    private String changePassLnk;
    public String getEndpoint() {
		return endpoint;
	}

	public void setEndpoint(String endpoint) {
		this.endpoint = endpoint;
	}

	public User getUser() {
        return user;
    }
    /*TODO APENAS PARA TESTES*/
	/*public static void main(String[] args) {
		LogonPromptDialog dialog = new LogonPromptDialog(null, true,"http://localhost:8082/AccessManagementWebService/services/LogonWS");
		dialog.setVisible(true);
	}*/

    /** Creates new form LogonPromptDialog */
    public LogonPromptDialog(java.awt.Frame parent, boolean modal,String endPoint,String changePass) {
        super(parent, modal);
        setEndpoint(endPoint);
        setChangePassLnk(changePass);
        initComponents();
        desenhaLink();
//        lbEsqueci.setVisible(Boolean.FALSE);
    }

    public String getChangePassLnk() {
		return changePassLnk;
	}

	public void setChangePassLnk(String changePassLnk) {
		this.changePassLnk = changePassLnk;
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      login = new javax.swing.JTextField();
      senha = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      lbEsqueci = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Login");
      setBounds(new java.awt.Rectangle(450, 300, 300, 150));

      senha.addKeyListener(new java.awt.event.KeyAdapter() {
         @Override
        public void keyPressed(java.awt.event.KeyEvent evt) {
            senhaKeyPressed(evt);
         }
      });

      jLabel1.setText("Login:");

      jLabel2.setText("Password:");

      jButton1.setText("OK");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("Cancel");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

     // jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_samarco.png"))); // NOI18N

      lbEsqueci.setForeground(new java.awt.Color(0, 102, 102));
      lbEsqueci.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      lbEsqueci.addMouseListener(new java.awt.event.MouseAdapter() {
         @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lbEsqueciMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel4)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(senha)
                     .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButton1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jButton2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                  .addComponent(lbEsqueci, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButton1)
                  .addComponent(jButton2))
               .addComponent(lbEsqueci, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        executarLogin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.INFO, "Good Bye");
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            executarLogin();
        }
    }//GEN-LAST:event_senhaKeyPressed

    private void lbEsqueciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEsqueciMouseClicked
          if(evt.getClickCount() > 0){
                try {
                    Process pc = Runtime.getRuntime().exec("cmd.exe /c start " + getChangePassLnk());
                } catch (IOException ex) {
                    Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
          }

    }//GEN-LAST:event_lbEsqueciMouseClicked

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel lbEsqueci;
   private javax.swing.JTextField login;
   private javax.swing.JPasswordField senha;
   // End of variables declaration//GEN-END:variables

    private void loadUser(String xmlContent) throws JAXBException {
        JAXBContext jaxbContext = JAXBContext
					.newInstance("com.hdntec.gestao.login.entity");
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

			ByteArrayInputStream inputStream = new ByteArrayInputStream(xmlContent.getBytes());

			this.user = (User) unmarshaller.unmarshal(inputStream);
    }

    /**
     * executa acao de verificar o login
     */
    private void executarLogin()
    {
        Service service = new Service();
        Call call;
        try {
        /*
            call = (Call) service.createCall();

            call.setTargetEndpointAddress(endpoint);
            QName name = new QName("login");
            call.setOperationName(name);
            String loginValue = this.login.getText();
            String senhaValue = new String(this.senha.getPassword());
            String ret = (String) call.invoke(new Object[]{loginValue, senhaValue});

            String code = ret.substring(0, 3);

            if ("400".equals(code)) {
                JOptionPane.showMessageDialog(this, BundleUtils.getMessage("msg.error.login"));
                this.senha.setText("");
            } else {
                String xml = ret.substring(3);
                if ("200".equals(code)) {
                    this.loadUser(xml);
                    this.setVisible(false);
                } else if ("500".equals(code)) {
                    int initMessage = xml.indexOf("<MESSAGE>") + "<MESSAGE>".length();
                    int endMessage = xml.indexOf("<\\MESSAGE>");
                    String message = xml.substring(initMessage, endMessage);
                    JOptionPane.showMessageDialog(this, BundleUtils.getMessage("msg.error.login.adm") + "\n" + message);
                } else {
                    JOptionPane.showMessageDialog(this, "Not recognized code: " + code);
                }
            }

    
*/
        	this.user = new User();
        	this.user.setId(1L);

        	this.user.setName("jesse");
        	
        	this.user.setNickname("jesse");
        	this.user.setEmail("jesse");
        	
        	this.user.setLogin("jesse");
        	// this.loadUser(xml);
             this.setVisible(false);

        } catch (Exception ex) {
            Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.SEVERE, null, ex);
        }	
       /* } catch (JAXBException ex) {
            Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ServiceException ex) {
            Logger.getLogger(LogonPromptDialog.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }


    public void executarLogout(String user) {
	    Service service = new Service();
	    Call call;
	    try {
	        call = (Call) service.createCall();

	        call.setTargetEndpointAddress(endpoint);
	        QName name = new QName("logout");
	        call.setOperationName(name);
	        String login = this.user.getLogin();
	        call.invoke(new Object[]{login});
	    }catch (Exception e) {
	    	System.out.println(e.getClass().getName());
			e.printStackTrace();
		}
   }

    private void desenhaLink(){
        lbEsqueci.setText("<html><body>" + "<a href=http://www.cflex.com.br >"+ BundleUtils.getMessage("msg.button.changepass") + "</a>"  + "</body></html>");
    }
}